Updates gcovr and sonar-scanner

diff --git a/sonar-scanner/bin/sonar-scanner b/sonar-scanner/bin/sonar-scanner
--- a/sonar-scanner/bin/sonar-scanner
+++ b/sonar-scanner/bin/sonar-scanner
@@ -28,7 +28,7 @@ sonar_scanner_home=$(dirname "$script_path")/..
 # make it fully qualified
 sonar_scanner_home=$(cd "$sonar_scanner_home" && pwd -P)
 
-jar_file=$sonar_scanner_home/lib/sonar-scanner-cli-3.2.0.1227.jar
+jar_file=$sonar_scanner_home/lib/sonar-scanner-cli-4.2.0.1873.jar
 
 # check that sonar_scanner_home has been correctly set
 if [ ! -f "$jar_file" ] ; then
@@ -47,6 +47,11 @@ then
   java_cmd="$JAVA_HOME/bin/java"
 else
   java_cmd="$(which java)"
+fi
+
+if [ -z "$java_cmd" -o ! -x "$java_cmd" ] ; then
+  echo "Could not find 'java' executable in JAVA_HOME or PATH."
+  exit 1
 fi
 
 project_home=$(pwd)
